### PR TITLE
Port library to jbuilder

### PR DESCRIPTION
**Pull request by rgrinberg**
The only downside of this change is that automatic printer installation isn't done in the toplevel. While that might be unfortunate, I think it's still worth switch to jbuilder.

### CODE REVIEW

**Comment by yallop** [comment]
Thanks for looking at this, @rgrinberg.  It looks like jbuilder doesn't work with older versions of OCaml (e.g. 4.01.0), which still need to be supported here.  (We _could_ maintain separate branches, one that uses jbuilder and works only with recent versions of OCaml, and one with support for older versions, but I'm not keen.)  So I'm fine with merging this eventually, but perhaps only when the library drops support for pre-jbuilder OCaml versions.

Is the automatic printer installation impossible with jbuilder?  It seems like a handy feature to have, even if there's some [debate about the appropriate mechanism](https://github.com/ocamllabs/ocaml-ctypes/issues/449).

**Comment by rgrinberg** [comment]
Ok, I understand. The requirement to support 4.01 is quite unusual though.
What's the use case for supporting such an old version?

**Comment by yallop** [comment]
It's just a reluctance to break things gratuitously.  There's been code deployed that uses ctypes/integers with OCaml 4.01, and I'd prefer not to force people to upgrade everything in order to use a new library release.

That said, I'm not planning to support 4.01 indefinitely, and I'll probably move to requiring 4.02 or later in a little while.

**Comment by yallop** [comment]
OCaml 4.01 support has been removed (#23), so the Travis check should pass if you rebase.

**Comment by rgrinberg** [comment]
Rebased, ported to dune, and to opam 2.0

**Comment by rgrinberg** [comment]
Looks the failure is on appveyor b/c opam 2.0 isn't available there. However, without opam 2.0, it's not possible to make releases.

**Comment by yallop** [comment]
There's an issue open to track OPAM 2.0 support on Appveyor: https://github.com/ocaml/ocaml-ci-scripts/issues/250

**Comment by yallop** [comment]
I'd like to merge this, but there are two outstanding issues:
 1. loading the printers in the top level.  Before this change integers print nicely by default:
     ```ocaml
     # UInt32.of_int 123;;
     - : uint32 = <uint32 123>
     ```
     but after the change they no longer have a useful printed representation:
     ```ocaml
     # UInt32.of_int 123;;
     - : uint32.t = <abstr>
     ```
     Further, loading the `integers.top` package fails:
     ```
     # #require "integers.top";;
     [...]
     Exception:
     Invalid_argument
      "The ocamltoplevel.cma library from compiler-libs cannot be loaded inside the OCaml toplevel".
    ```

   2. This change introduces a new top-level module `Integers` (so that we now have `Integers.Unsigned.UInt32` rather than `Unsigned.UInt32`, for example).  I'd prefer not to have this new module, since it breaks backwards compatibility.

@rgrinberg: do you think these issues can be resolved?

**Comment by avsm** [comment]
have you tried utop-full?

**Comment by yallop** [comment]
I think what's happening is that the `Install_integer_printers` module is loaded/initialized before the `Integer_printers` module, since there's no dependency between them.

The following fixes the problem:

```diff
diff --git a/top/dune b/top/dune
index 37a42691..a187464b 100644
--- a/top/dune
+++ b/top/dune
@@ -4,4 +4,4 @@
  (modes byte)
  (wrapped false)
  (synopsis "toplevel pretty printers")
- (libraries integers compiler-libs.toplevel))
+ (libraries integers compiler-libs))
diff --git a/top/install_integer_printers.ml b/top/install_integer_printers.ml
index 17a18919..2b8b3ef8 100644
--- a/top/install_integer_printers.ml
+++ b/top/install_integer_printers.ml
@@ -1,5 +1,7 @@
 (* Adapted from Anil Madhavapeddy's ocaml-uri package. *)
 
+let _ = Integer_printers.format_sint
+
 let printers = [ "Integer_printers.format_sint";
                  "Integer_printers.format_long";
                  "Integer_printers.format_llong";
```

I'd send a PR, but perhaps there's a way to record the dependency in the `dune` file rather than faking it in the module implementation.

**Comment by rgrinberg** [comment]
Thanks for the help. That should do it I guess.

The bit about switching to `compiler-libs` from `compiler-libs.toplevel` is strange to me. `compiler-libs.toplevel` is what I copied from @avsm's code in ocaml-uri. Is there a mistake there as well?

> I'd send a PR, but perhaps there's a way to record the dependency in the dune file rather than faking it in the module implementation.

There's no way to do this at the moment. Your workaround is what I usually use.

**Comment by yallop** [comment]
> Thanks for the help. That should do it I guess.

I've sent a PR: https://github.com/rgrinberg/ocaml-integers/pull/1

> The bit about switching to `compiler-libs` from `compiler-libs.toplevel` is strange to me. `compiler-libs.toplevel` is what I copied from @avsm's code in `ocaml-uri`. Is there a mistake there as well?

It seems so.  Here's what I see with OCaml 4.07.0 and `uri.2.0.0`:

```
# #require "uri.top";;
[...]
Exception:
Invalid_argument
 "The ocamltoplevel.cma library from compiler-libs cannot be loaded inside the OCaml toplevel".
```

**Comment by yallop** [comment]
Thank you for your patience, and for the contribution!

**Comment by rgrinberg** [comment]
> One change I didn't spot earlier: the shared object is now called dllintegers_stubs.so rather than dllintegers.so. Is that easy to change back?

It's not possible unfortunately. This is a convention that dune imposes on all packages. 

> It's possible to adapt ctypes (and, perhaps, the other packages that use integers) for the new name, but it's a bit of work. For every package that depends on integers we'll have to

How does ctypes depend on `dllintegers.so`? I just tried building ctypes with this branch and it seems to work.

**Comment by avsm** [comment]
Thanks for noticing the uri breakage as well; I've opened up https://github.com/mirage/ocaml-uri/issues/129 to track this.

**Pull request merged**
